<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59018328"><DocLocation><![CDATA[C:\Users\SHCHATTI\Documents\Unified Functional Testing\demo_Orange]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[demo_Orange]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:01]]></Time>
<TimeTick>1676005021</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:01]]></Time>
<TimeTick>1676005021</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:01]]></Time>
<TimeTick>1676005021</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Login" SourceLine="0" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e5cd999eac263e4be3617db92f54f9864ce6a0873f"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:01]]></Time>
<TimeTick>1676005021</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Login" SourceLine="1" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:01]]></Time>
<TimeTick>1676005021</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Login" SourceLine="2" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:26:59" eTime="10-02-2023 - 10:27:01" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[search]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:03]]></Time>
<TimeTick>1676005023</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:03]]></Time>
<TimeTick>1676005023</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Time"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:03]]></Time>
<TimeTick>1676005023</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="search" SourceLine="0" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Time.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:03]]></Time>
<TimeTick>1676005023</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="search" SourceLine="1" >
<Disp><![CDATA[Time.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:04]]></Time>
<TimeTick>1676005024</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:04]]></Time>
<TimeTick>1676005024</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" Source="search" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_2.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="33" Source="search" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[OrangeHRM.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:04]]></Time>
<TimeTick>1676005024</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="36" Source="search" SourceLine="3" >
<Disp><![CDATA[OrangeHRM.Back]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="25" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:27:01" eTime="10-02-2023 - 10:27:06" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="21" >
<Disp><![CDATA[search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T18">
<AName><![CDATA[Employe_list]]></AName>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:07]]></Time>
<TimeTick>1676005027</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:07]]></Time>
<TimeTick>1676005027</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Admin.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:07]]></Time>
<TimeTick>1676005027</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="Employe_list" SourceLine="0" >
<Disp><![CDATA[Admin.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" Source="Employe_list" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:09]]></Time>
<TimeTick>1676005029</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:09]]></Time>
<TimeTick>1676005029</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="49" Source="Employe_list" SourceLine="1" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" Source="Employe_list" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:10]]></Time>
<TimeTick>1676005030</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Employee List.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:10]]></Time>
<TimeTick>1676005030</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" Source="Employe_list" SourceLine="2" >
<Disp><![CDATA[Employee List.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Type for hints....Set]]></Obj>
<Details plainTxt="False" ><![CDATA["shilpa"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="58" Source="Employe_list" SourceLine="3" >
<Disp><![CDATA[Type for hints....Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0555"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="61" Source="Employe_list" SourceLine="4" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" Source="Employe_list" SourceLine="5" >
<Disp><![CDATA[WebElement.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[IncludeCurrent Employees.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" Source="Employe_list" SourceLine="6" >
<Disp><![CDATA[IncludeCurrent Employees.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="70" Source="Employe_list" SourceLine="7" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" Source="Employe_list" SourceLine="8" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="76" Source="Employe_list" SourceLine="9" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="79" Source="Employe_list" SourceLine="10" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" Source="Employe_list" SourceLine="11" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" Source="Employe_list" SourceLine="12" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="88" Source="Employe_list" SourceLine="13" >
<Disp><![CDATA[OrangeHRM_3.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="53" Source="Employe_list" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[OrangeHRM.Back]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:12]]></Time>
<TimeTick>1676005032</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="90" Source="Employe_list" SourceLine="14" >
<Disp><![CDATA[OrangeHRM.Back]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="42" Source="Employe_list" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:27:06" eTime="10-02-2023 - 10:27:14" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="38" >
<Disp><![CDATA[Employe_list Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T38">
<AName><![CDATA[Add_employe]]></AName>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:14]]></Time>
<TimeTick>1676005034</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:14]]></Time>
<TimeTick>1676005034</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Add Employee.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:14]]></Time>
<TimeTick>1676005034</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="97" Source="Add_employe" SourceLine="0" >
<Disp><![CDATA[Add Employee.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="96" Source="Add_employe" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:16]]></Time>
<TimeTick>1676005036</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["nandini"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:16]]></Time>
<TimeTick>1676005036</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="102" Source="Add_employe" SourceLine="1" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[middleName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:16]]></Time>
<TimeTick>1676005036</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="105" Source="Add_employe" SourceLine="2" >
<Disp><![CDATA[middleName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["s"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:16]]></Time>
<TimeTick>1676005036</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="108" Source="Add_employe" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0333"]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:16]]></Time>
<TimeTick>1676005036</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="111" Source="Add_employe" SourceLine="4" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:16]]></Time>
<TimeTick>1676005036</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="114" Source="Add_employe" SourceLine="5" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="101" Source="Add_employe" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:36]]></Time>
<TimeTick>1676005056</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Nickname]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Nickname"&nbsp;(of&nbsp;class&nbsp;WebElement).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:36]]></Time>
<TimeTick>1676005056</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Nickname]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebElement<br>Index = 0<br>Html Tag = DIV<br>_xpath = //DIV[2]/DIV[1]/FORM[1]/DIV[1]/DIV[2]<br>|Visible = -1<br>innertext = Nickname<br>Html Id = <br>DHTML Class = oxd-grid-3 orangehrm-full-width-grid<br>acc_name = <br>]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:36]]></Time>
<TimeTick>1676005056</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="160" status="Warning" nType="Description" Source="Add_employe" SourceLine="6" >
<Disp><![CDATA[Nickname]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="159" status="Failed" nType="Run Error" Source="Add_employe" SourceLine="6" >
<Disp><![CDATA[Nickname]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="158" status="Failed" Source="Add_employe" SourceLine="6" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="95" status="Failed" Source="Add_employe" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:36]]></Time>
<TimeTick>1676005056</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Nickname&quot; (of class WebElement).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (7): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM_3&quot;).WebElement(&quot;Nickname&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:37]]></Time>
<TimeTick>1676005057</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="162" status="Failed" Source="Add_employe" SourceLine="6" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[10-02-2023 - 10:27:55]]></Time>
<TimeTick>1676005075</TimeTick>
<NodeArgs eType="General" icon="12" nRep="163" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="161" status="Failed" Source="Add_employe" SourceLine="6" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:27:14" eTime="10-02-2023 - 10:27:55" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="92" status="Failed" >
<Disp><![CDATA[Add_employe Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[demo_Orange Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10-02-2023 - 10:26:58" eTime="10-02-2023 - 10:27:55" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test demo_Orange Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>