<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59018328"><DocLocation><![CDATA[C:\Users\SHCHATTI\Documents\Unified Functional Testing\Demo_Tricentis]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Demo_Tricentis]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[07-02-2023 - 10:40:30]]></Time>
<TimeTick>1675746630</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA["Demo Web Shop"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Demo Web Shop<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Demo Web Shop<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://demowebshop.tricentis.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Demo Web Shop<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[07-02-2023 - 10:40:30]]></Time>
<TimeTick>1675746630</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" Source="Login" SourceLine="0" >
<Disp><![CDATA["Demo Web Shop"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-02-2023 - 10:40:50]]></Time>
<TimeTick>1675746650</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Log in]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Log&nbsp;in"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[07-02-2023 - 10:40:50]]></Time>
<TimeTick>1675746650</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log in]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //LI/A[normalize-space()="Log in"]<br>|Visible = -1<br>Text = Log in<br>Name = Log in<br>Html Id = <br>Href = https://demowebshop.tricentis.com/login<br>DHTML Class = ico-login<br>acc_name = <br>]]></Details>
<Time><![CDATA[07-02-2023 - 10:40:50]]></Time>
<TimeTick>1675746650</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" status="Warning" nType="Description" Source="Login" SourceLine="0" >
<Disp><![CDATA[Log in]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="55" status="Failed" nType="Run Error" Source="Login" SourceLine="0" >
<Disp><![CDATA[Log in]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="54" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[07-02-2023 - 10:40:50]]></Time>
<TimeTick>1675746650</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Log in&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (1): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop&quot;).Link(&quot;Log in&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[07-02-2023 - 10:40:50]]></Time>
<TimeTick>1675746650</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-02-2023 - 10:41:41]]></Time>
<TimeTick>1675746701</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Log in]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Log&nbsp;in"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[07-02-2023 - 10:41:41]]></Time>
<TimeTick>1675746701</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Log in]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //LI/A[normalize-space()="Log in"]<br>|Visible = -1<br>Text = Log in<br>Name = Log in<br>Html Id = <br>Href = https://demowebshop.tricentis.com/login<br>DHTML Class = ico-login<br>acc_name = <br>]]></Details>
<Time><![CDATA[07-02-2023 - 10:41:41]]></Time>
<TimeTick>1675746701</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" status="Warning" nType="Description" Source="Login" SourceLine="0" >
<Disp><![CDATA[Log in]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="63" status="Failed" nType="Run Error" Source="Login" SourceLine="0" >
<Disp><![CDATA[Log in]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="57" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[07-02-2023 - 10:41:41]]></Time>
<TimeTick>1675746701</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Log in&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (1): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop&quot;).Link(&quot;Log in&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[07-02-2023 - 10:41:41]]></Time>
<TimeTick>1675746701</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="66" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-02-2023 - 10:42:38]]></Time>
<TimeTick>1675746758</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Log in]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Log&nbsp;in"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[07-02-2023 - 10:42:38]]></Time>
<TimeTick>1675746758</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Log in]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //LI/A[normalize-space()="Log in"]<br>|Visible = -1<br>Text = Log in<br>Name = Log in<br>Html Id = <br>Href = https://demowebshop.tricentis.com/login<br>DHTML Class = ico-login<br>acc_name = <br>]]></Details>
<Time><![CDATA[07-02-2023 - 10:42:38]]></Time>
<TimeTick>1675746758</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="113" status="Warning" nType="Description" Source="Login" SourceLine="0" >
<Disp><![CDATA[Log in]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="112" status="Failed" nType="Run Error" Source="Login" SourceLine="0" >
<Disp><![CDATA[Log in]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="111" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="65" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[07-02-2023 - 10:42:38]]></Time>
<TimeTick>1675746758</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Log in&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (1): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop&quot;).Link(&quot;Log in&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[07-02-2023 - 10:42:38]]></Time>
<TimeTick>1675746758</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="115" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:04]]></Time>
<TimeTick>1675746784</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Email]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Email"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:04]]></Time>
<TimeTick>1675746784</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Email]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //INPUT[@id="Email"]<br>|rows = 0<br>placeholder = <br>Name = Email<br>Max Length = 524288<br>Html Id = Email<br>default value = <br>DHTML Class = email<br>acc_name = <br>]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:04]]></Time>
<TimeTick>1675746784</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="121" status="Warning" nType="Description" Source="Login" SourceLine="0" >
<Disp><![CDATA[Email]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="120" status="Failed" nType="Run Error" Source="Login" SourceLine="0" >
<Disp><![CDATA[Email]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="119" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="114" status="Failed" Source="Login" SourceLine="0" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:04]]></Time>
<TimeTick>1675746784</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Email&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (2): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop. Login&quot;).WebEdit(&quot;Email&quot;).Set &quot;chattishilpa61@gmail.com&quot;&quot;. ]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:04]]></Time>
<TimeTick>1675746784</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="123" status="Failed" Source="Login" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:29]]></Time>
<TimeTick>1675746809</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Password"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:29]]></Time>
<TimeTick>1675746809</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Password]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = password<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //INPUT[@id="Password"]<br>|rows = 0<br>placeholder = <br>Name = Password<br>Max Length = 524288<br>Html Id = Password<br>default value = <br>DHTML Class = password<br>acc_name = <br>]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:29]]></Time>
<TimeTick>1675746809</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="170" status="Warning" nType="Description" Source="Login" SourceLine="1" >
<Disp><![CDATA[Password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="169" status="Failed" nType="Run Error" Source="Login" SourceLine="1" >
<Disp><![CDATA[Password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="168" status="Failed" Source="Login" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="122" status="Failed" Source="Login" SourceLine="1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:29]]></Time>
<TimeTick>1675746809</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Password&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (3): &quot;Browser(&quot;Demo Web Shop&quot;).Page(&quot;Demo Web Shop. Login&quot;).WebEdit(&quot;Password&quot;).SetSecure &quot;63e1dc320c75d0e186bdcc7ad1b1cc11301555af&quot;&quot;. ]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:29]]></Time>
<TimeTick>1675746809</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="172" status="Failed" Source="Login" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[07-02-2023 - 10:43:35]]></Time>
<TimeTick>1675746815</TimeTick>
<NodeArgs eType="General" icon="11" nRep="173" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="171" status="Failed" Source="Login" SourceLine="2" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="07-02-2023 - 10:40:29" eTime="07-02-2023 - 10:43:35" passed="0" failed="10" warnings="5" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Demo_Tricentis Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="07-02-2023 - 10:40:26" eTime="07-02-2023 - 10:43:36" passed="0" failed="10" warnings="5" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Demo_Tricentis Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>